# Generated by Django 4.2 on 2023-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(default='None', max_length=20)),
            ],
            options={
                'db_table': 'all_users',
            },
        ),
    ]
