# Generated by Django 4.2 on 2023-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writemodel',
            name='title',
            field=models.CharField(default='무제', max_length=30),
        ),
    ]
