# Generated by Django 4.2 on 2023-04-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_content', models.CharField(default='', max_length=256, verbose_name='컨텐츠 제목')),
                ('text_content', models.CharField(default='', max_length=1000, verbose_name='컨텐츠 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='컨텐츠 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='컨텐츠 수정일')),
                ('is_liked', models.IntegerField(verbose_name='종아요 수')),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Isliked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head_page.pagemodel')),
            ],
        ),
    ]
